mod1/urls.py
from django.conf.urls import url
from . import views
from mod1 import views as core_views
from django.contrib.auth.views import logout
app_name = 'mod1'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', core_views.register, name='register'),
    url(r'^home/$', views.home, name='home'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
     url(r'^oracle/$', views.oracle, name='oracle'),
     url(r'^mysql/$', views.mysql, name='mysql'),
     url(r'^mariadb/$', views.mariadb, name='mariadb'),
      url(r'^postgres/$', views.postgres, name='postgres'),
      url(r'^mysqllambda/$', views.mysqllambda, name='mysqllambda'),
      url(r'^myaccount/$', views.myaccount, name='myaccount'),
      url(r'^about/$', views.about, name='about'),
      url(r'^aurora/$', views.aurora, name='aurora'),
      url(r'^redshift/$', views.redshift, name='redshift'),
      url(r'^sqlserver/$', views.sqlserver, name='sqlserver'),
      url(r'^mysqlsup/$', views.mysqlsup  , name='mysqlsup'),
      url(r'^rdssup/$', views.rdssup  , name='rdssup'),
      url(r'^rds/$',  views.rds  , name='rds'),
      url(r'^rdsadvan/$',  views.rdsadvan  , name='rdsadvan'),
       url(r'^database/$',  views.database  , name='database'),

 
 

    ]

xray/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mod1/', include('mod1.urls')),
    url(r'^', include('mod1.urls')),

]

mod1/models.py
from django.db import models

# Create your models here.

mod1/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, widget=forms.TextInput(
            attrs={
                'style': 'border-color: blue; color:deepskyblue;',
                'placeholder': 'Write your name here'
            }))
    first_name = forms.CharField(max_length=30, required=False, help_text='Enter your full name.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    address=forms.CharField(max_length=500,required=False,help_text='enter address')
    oraganization=forms.CharField(max_length=50,required=True,help_text='please enter the company')
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2','address','oraganization' )

class userloginform(forms.Form):
	username=forms.CharField(widget=forms.TextInput(
            attrs={
                'style': 'border-color: blue;float:centre;'
            }),label='username')
	password=forms.CharField(label=' password',widget=forms.PasswordInput(attrs={'style': 'float:centre'}))

	class Meta:
		model=User
		fields=('username','password')

mod1/views.py
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.contrib.auth import authenticate,logout
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from .forms import SignUpForm,userloginform
from django.contrib.auth import login as auth_login
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
def index(request):
		return render(request, 'mod1/index.html')
'''def register(request):
	return render(request,'mod1/register.html')'''

#def login(request):
	#return render(request,'mod1/login.html')

def home(request):
	return render(request,'mod1/home.html')
def register(request):
	if request.method == 'POST':
		form = SignUpForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username, password=raw_password)
			auth_login(request, user)
			return render(request,'mod1/home.html')
	else:
		form = SignUpForm()
	c={'form':form}
	return render(request, 'mod1/register.html',c)

def user_login(request):
	if request.method== 'POST':
		form=userloginform(request.POST)
		if form.is_valid():
			username=request.POST['username']
			password=request.POST['password']
			user=authenticate(username=username,password=password)
			if user:
				if user.is_active:
					auth_login(request,user)
					request.session['username'] = username
					return redirect('mod1:home')
	else:
		form = userloginform()
	context={
	'form':form,
	}
	return render(request,'mod1/login.html',context)

def user_logout(request):
	logout(request)
	return redirect('index')
def oracle(request):
	return render(request,'mod1/oracle.html')

def mysql(request):
	return render(request,'mod1/mysql.html')

def mariadb(request):
	return render(request,'mod1/mariadb.html')

def postgres(request):
	return render(request,'mod1/postgres.html')

def mysqllambda(request):
	return render(request,'mod1/mysqllambda.html')

def myaccount(request):
	username = None
	if not request.user.is_authenticated:
		return render(request, 'mod1/login.html')
	else:
		username = request.user.username
		email=request.user.email
		return render(request, 'mod1/myaccount.html', {'username': username, 'email': email})

def about(request):
	return render(request, 'mod1/about.html')


def aurora(request):
	return render(request, 'mod1/aurora.html')


def redshift(request):
	return render(request, 'mod1/redshift.html')


def sqlserver(request):
	return render(request, 'mod1/sqlserver.html')

def mysqlsup(request):
	return render(request, 'mod1/mysqlsup.html')	

def rdssup(request):
	return render(request, 'mod1/rdssup.html')	

def rds(request):
	return render(request, 'mod1/rds.html')	

def rdsadvan(request):
	return render(request, 'mod1/rdsadvan.html')	


def database(request):
	return render(request, 'mod1/database.html')	

mod1/templates/mod1/aurora.html
{% extends 'mod1/base3.html' %}
{% block body %}
 <div class="container" style="background-color: #383838;">
    <div class="row" style="color: white; margin-top: 70px;font-size: 18px;">

   <div class="col-md-6">
      <div class="embed-responsive embed-responsive-4by3" >
          <iframe width="560" height="315" src="https://www.youtube.com/embed/_oWa4fWAqTY" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>
       </div>   
      <div>
          <div style="text-align: justify; margin-right: 20px; margin-left: 20px;">
              Amazon Aurora is a MySQL and PostgreSQL compatible relational database built for the cloud, that combines the performance and availability of high-end commercial databases with the simplicity and cost-effectiveness of open source databases.<br/>

               Aurora is up to five times faster than standard MySQL databases and three times faster than standard PostgreSQL databases. It provides the security, availability, and reliability of commercial-grade databases at 1/10th the cost. Aurora is fully managed by Amazon Relational Database Service (RDS), which automates time-consuming administration tasks like hardware provisioning, database setup, patching, and backups.<br/>

               Aurora features a distributed, fault-tolerant, self-healing storage system that auto-scales up to 64TB per database instance. Aurora delivers high performance and availability with up to 15 low-latency read replicas, point-in-time recovery, continuous backup to Amazon S3, and replication across three Availability Zones.<br/>
                
                Amazon Aurora is a hosted relational database service developed and offered by Amazon.Aurora is available as part of the Amazon Relational Database Service (RDS). Although it is a proprietary technology,it is based on the open-source MySQL database.<br/>
                Aurora does not require the user to provision database storage, as it automatically allocates storage in 10-gigabyte increments, as needed, up to a maximum of 64 terabytes.Aurora offers automatic, six-way replication of those 10-gigabyte chunks across multiple locations for improved availability and fault-tolerance. Aurora also provides users with more comprehensive performance metrics, such as query throughput and latency, as compared to other RDS database engines.<br/>
                Amazon designed Aurora to be compatible with MySQL, meaning that tools for querying or managing MySQL databases (such as the mysql command-line client and the MySQL Workbench graphical user-interface) work with Amazon Aurora databases as well. Not all MySQL options and features are available, however: as of September  2016, Amazon Aurora is only compatible with one version of MySQL (5.6), and supports only InnoDB as a storage engine.<br/>
                Amazon claims fivefold performance improvements on benchmarking tests, due to "tightly integrating the database engine with an SSD-based virtualized storage layer purpose-built for database workloads, reducing writes to the storage system, minimizing lock contention and eliminating delays created by database process threads".Other independent tests have shown that Aurora performs better than competing technologies on some, but not all, combinations of workload and instance type.<br/>
               

                <b><h2>Customers</h2></b>
                General Electric, Nasdaq, Expedia, Ticketmaster, Pearson etc.


                
     </div>
    </div>
   </div>
  </div>
   <div class="f1" style="color:white;">
      <footer class="site-footer row" style=" background: black; padding-left: 20px;">
       <div class="col-md-6"> <h3>Contact us<br></h3>
          <p>  Email: abc@amazon.com<br>
               Mobile no: +919906810610,+919797108430</p>
       </div>
       <div class="col-md-6" style="text-align: right; padding-right: 50px; padding-top: 20px;">
        <a style="padding-right: 20px; color: white;" href="{% url 'mod1:rdsadvan' %}">Why RDS?</a>
        <a style="color: white;" href="{% url 'mod1:database' %}">Advantages of Database in cloud</a>
       </div> 
      </footer>
    </div>
           

           
       
       
   {% endblock %}















        

mod1/templates/mod1/base2.html
{% load  staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>RDS Documentation</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'mod1/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'mod1/css/style.css' %}"/>
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
   <script src="{%static 'mod1/js/bootstrap.min.js' %}"></script>
  </head>

  <body style="background-image: url(../../static/mod1/images/main1.png); background-attachment: fixed;">
     <!-- Codrops top bar -->
            <div class="codrops-top">
                <a href="http://tympanus.net/Development/RockingLetters/">
                    <strong>&laquo; RDS Helpdesk: </strong>Learn about Common Support Issues
                </a>
                <span class="right">
                    <a href="http://www.flickr.com/photos/markjsebastian/">Home</a>
                    <a href="http://creativecommons.org/licenses/by-sa/2.0/deed.en">About</a>
                    <a href="http://tympanus.net/codrops/2012/01/02/fullscreen-background-image-slideshow-with-css3/">
                        Myaccount
                    </a>
                     <a href="http://tympanus.net/codrops/2012/01/02/fullscreen-background-image-slideshow-with-css3/">
                        Logout
                    </a>
                </span>
                <div class="clr"></div>
            </div><!--/ Codrops top bar -->
   
<!--Navbar End-->
{% block body %}
    {% endblock %}

 <div class="f1" style="color:white;">
      <footer class="site-footer row" style=" background: black; padding-left: 20px;">
       <div class="col-md-6"> <h3>Contact us<br></h3>
          <p>  Email: abc@amazon.com<br>
               Mobile no: +919906810610,+919797108430</p>
       </div>
       <div class="col-md-6" style="text-align: right; padding-right: 50px; padding-top: 20px;">
        <a style="padding-right: 20px; color: white;" href="{% url 'mod1:rdsadvan' %}">Why RDS?</a>
        <a style="color: white;" href="{% url 'mod1:database' %}">Advantages of Database in cloud</a>
       </div> 
      </footer>
    </div>
  </body>
</html>

mod1/templates/mod1/base3.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Oracle</title>
    <!-- Bootstrap -->
    <meta name="author" content="Codrops" />
    <link rel="stylesheet" type="text/css" href="{% static 'mod1/css/bootstrap.min.css' %}"/>
       <link rel="stylesheet" type="text/css" href="{% static 'mod1/css/style.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'mod1/css/demo.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'mod1/css/style1.css' %}" />
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
     <script type="text/javascript" src="{% static 'mod1/js/modernizr.custom.86080.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
  
  </head>
   <body style="background-image: url(../../static/mod1/images/main1.png); background-attachment: fixed;">
    <!--Navbar start-->
    <!-- Codrops top bar--> 
            <div class="codrops-top" style="margin-top: 0px; position: fixed;">
                <a>
                    <strong>&laquo; RDS Helpdesk: </strong>Learn about Common Support Issues
                </a>
                <span class="right" style="margin-right: 15px;">
                    <a href="{% url 'mod1:home' %}">Home</a>
                    <a href="#about1">About</a>
                    <a href="{% url 'mod1:myaccount' %}">
                        Myaccount
                    </a>
                     <a href="{% url 'mod1:index' %}">
                        Logout
                    </a>
                </span>
                <div class="clr"></div>
            </div><!--/ Codrops top bar -->
         
              {% block body %}
              {% endblock %}
             
    </body>
</html>

mod1/templates/mod1/index.html
{% extends 'mod1/base1.html' %}

{% block body %}
<div style="margin-top: 280px;">
  <center  style="padding-top: 20px;"><h1>Welcome to Amazon RDS Common Support Issues Website.</h1></center>
  <center><h3>Amazon Relational Database Service (Amazon RDS) is a web service that makes it easier<br/> to set up, operate, and scale a relational database in the cloud.</h3></center><br>
  <div style="margin-top: 200px;">
  <center><h4>Get free and easy excess to know how to resolve the Common support issues in RDS.</h4></center>
  <center><a style="padding-left: 50px; padding-right: 50px;" class="btn btn-lg btn-default" href="{% url 'mod1:register' %}" role="button">Register</a>
  <a style="padding-left: 50px; padding-right: 50px;" class="btn btn-lg btn-default" href="{% url 'mod1:login' %}" role="button">Login</a></center>
  <center><h4>No charges. Unsubscribe anytime.</h4> </center>
</div>
</div>
{% endblock %}          

mod1/templates/mod1/myaccount.html
{% extends 'mod1/base3.html'%}
{% block body %}
<div style="padding-left: 800px; padding-top: 300px; padding-right: 850px; font-size: 20px; padding-bottom: 250px;">
  <h3 style="background-color: yellow;"> Username: {{user.username}}
   </br></br>
Email: {{user.email}}</h3>
</div>
 <div class="f1" style="color:white; position: fixed;">
      <footer class="site-footer row" style=" background: black; padding-left: 20px;">
       <div class="col-md-6"> <h3>Contact us<br></h3>
          <p>  Email: abc@amazon.com<br>
               Mobile no: +919906810610,+919797108430</p>
       </div>
       <div class="col-md-6" style="text-align: right; padding-right: 50px; padding-top: 20px;">
        <a style="padding-right: 20px; color: white;" href="{% url 'mod1:rdsadvan' %}">Why RDS?</a>
        <a style="color: white;" href="{% url 'mod1:database' %}">Advantages of Database in cloud</a>
       </div> 
      </footer>
    </div>
{% endblock%}

mod1/templates/mod1/mysql.html
{% extends 'mod1/base3.html' %}
{% block body %}
<style type="text/css">
  .alpha60 {
    filter: alpha(opacity=90);
  filter: progid: DXImageTransform.Microsoft.Alpha(opacity=90);
  -moz-opacity: 0.00;
  opacity: 0.9;
}
</style>
<div class="container alpha60" style="background-color: #383838;">
    <div class="row" style="color: white; margin-top: 70px;font-size: 18px;">

   <div class="col-md-6">
      <div class="embed-responsive embed-responsive-4by3" >
          <iframe width="560" height="315" src="https://www.youtube.com/embed/DCaA1-EcTMk"></iframe></div>
       </div>   
      <div>
           <div style="text-align: justify; margin-right: 20px; margin-left: 20px;">
             MySQL (officially pronounced as /maɪ ˌɛskjuːˈɛl/ "My S-Q-L") is an open-source relational database management system (RDBMS).Its name is a combination of "My", the name of co-founder Michael Widenius's daughter, and "SQL", the abbreviation for Structured Query Language. The MySQL development project has made its source code available under the terms of the GNU General Public License, as well as under a variety of proprietary agreements. MySQL was owned and sponsored by a single for-profit firm, the Swedish company MySQL AB, now owned by Oracle Corporation.For proprietary use, several paid editions are available, and offer additional functionality.<BR>
            MySQL is a central component of the LAMP open-source web application software stack (and other "AMP" stacks). LAMP is an acronym for "Linux, Apache, MySQL, Perl/PHP/Python". Applications that use the MySQL database include: TYPO3, MODx, Joomla, WordPress, Simple Machines Forum, phpBB, MyBB, and Drupal. MySQL is also used in many high-profile, large-scale websites, including Google(though not for searches), Facebook, Twitter, Flickr, and YouTube.<BR>
            MySQL was created by a Swedish company, MySQL AB, founded by David Axmark, Allan Larsson and Michael "Monty" Widenius. Original development of MySQL by Widenius and Axmark began in 1994. The first version of MySQL appeared on 23 May 1995. It was initially created for personal usage from mSQL based on the low-level language ISAM, which the creators considered too slow and inflexible. They created a new SQL interface, while keeping the same API as mSQL. By keeping the API consistent with the mSQL system, many developers were able to use MySQL instead of the (proprietarily licensed) mSQL antecedent.[citation needed][dubious – discuss]<br><br>
           <b><h2> Milestones</h2></b><hr>

        Additional milestones in MySQL development included:<br>

    <li>First internal release on 23 May 1995.</li>
   <li>Version 3.19: End of 1996, from www.tcx.se.</li>
    <li>Version 3.20: January 1997.</li>
  <li>Windows version was released on 8 January 1998 for Windows 95 and NT.</li>
  <li> Version 3.21: production release 1998, from www.mysql.com.</li>
 <li> Version 3.22: alpha, beta from 1998.</li>
 <li> Version 3.23: beta from June 2000, production release 22 January 2001.</li>
  vVersion 4.0: beta from August 2002, production release March 2003 (unions).</li>
 <li> Version 4.01: beta from August 2003, Jyoti[clarification needed][citation needed] adopts MySQL for database tracking.</li>
  <li> Version 4.1: beta from June 2004, production release October 2004 (R-trees and B-trees, subqueries, prepared statements).</li>
   <li>Version 5.0: beta from March 2005, production release October 2005 (cursors, stored procedures, triggers, views, XA transactions).</li>

    The developer of the Federated Storage Engine states that "The Federated Storage Engine is a proof-of-concept storage engine",but the main distributions of MySQL version 5.0 included it and turned it on by default. Documentation of some of the short-comings appears in "MySQL Federated Tables: The Missing Manual".

   <li> Sun Microsystems acquired MySQL AB in 2008.</li>
  <li> Version 5.1: production release 27 November 2008 (event scheduler, partitioning, plugin API, row-based replication, server log tables).</li>

    Version 5.1 contained 20 known crashing and wrong result bugs in addition to the 35 present in version 5.0 (almost all fixed as of release 5.1.51).[32]
    MySQL 5.1 and 6.0-alpha showed poor performance when used for data warehousing – partly due to its inability to utilize multiple CPU cores for processing a single query.

   <li>Oracle acquired Sun Microsystems on 27 January 2010.</li>
  <li> The day Oracle announced the purchase of Sun, Michael "Monty" Widenius forked MySQL, launching MariaDB, and took a swath of MySQL developers with him.</li>
  <li> MySQL Server 5.5 was generally available (as of December 2010).Enhancements and features include:
      <li>The default storage engine is InnoDB, which supports transactions and referential integrity constraints.</li>
      <li>Improved InnoDB I/O subsystem.</li>
      Improved SMP support,
       <li> Semisynchronous replication.</li>
      <li> SIGNAL and RESIGNAL statement in compliance with the SQL standard.</li>
      <li> Support for supplementary Unicode character sets utf16, utf32, and utf8mb4.</li>
      <li> New options for user-defined partitioning.</li>
  <li> MySQL Server 6.0.11-alpha was announced on 22 May 2009 as the last release of the 6.0 line. Future MySQL Server development uses a New Release Model. Features developed for 6.0 are being incorporated into future releases.</li>
   <li> The general availability of MySQL 5.6 was announced in February 2013. New features included performance improvements to the query optimizer, higher transactional throughput in InnoDB, new NoSQL-style memcached APIs, improvements to partitioning for querying and managing very large tables, TIMESTAMP column type that correctly stores milliseconds, improvements to replication, and better performance monitoring by expanding the data available through the PERFORMANCE_SCHEMA.The InnoDB storage engine also included support for full-text search and improved group commit performance.</li>
    <li>The general availability of MySQL 5.7 was announced in October 2015.</li>
   <li>MySQL Server 8.0.0-dmr (Milestone Release) was announced 12 September 2016.</li>
       </div> 
            </div><hr>
                  <div class="row" id="SupButton">
              <a style=" margin-left: 300px; align-content: center;margin-top: 10px; " class="btn btn-lg btn-default" href="#" role="button"> Link</a>
                 <a style="margin-left: 250px;" class="btn btn-lg btn-default" href="{% url 'mod1:mysqlsup' %}"" role="button"> Common Support issues</a>
            </div>
    
    
   </div>
  </div>

   <div class="f1" style="color:white;">
      <footer class="site-footer row" style=" background: black; padding-left: 20px;">
       <div class="col-md-6"> <h3>Contact us<br></h3>
          <p>  Email: abc@amazon.com<br>
               Mobile no: +919906810610,+919797108430</p>
       </div>
       <div class="col-md-6" style="text-align: right; padding-right: 50px; padding-top: 20px;">
        <a style="padding-right: 20px; color: white;" href="{% url 'mod1:rdsadvan' %}">Why RDS?</a>
        <a style="color: white;" href="{% url 'mod1:database' %}">Advantages of Database in cloud</a>
       </div> 
      </footer>
    </div>
           
    </li>
     </div>
    </div>
   </div>
  </div>
           

           
       
       
   {% endblock %}




















   

mod1/templates/mod1/rds.html
{% extends 'mod1/base3.html' %}
{% block body %}
  <style type="text/css">
  .alpha60 {
    filter: alpha(opacity=90);
  filter: progid: DXImageTransform.Microsoft.Alpha(opacity=90);
  -moz-opacity: 0.90;
  opacity: 0.9;
}
</style>
 <div class="container alpha60" style="background-color: #383838;">
    <div class="row" style="color: white; margin-top: 70px;font-size: 18px;">


   <div class="col-md-6">
      <div class="embed-responsive embed-responsive-4by3" >
          <iframe width="560" height="315" src="https://www.youtube.com/embed/yjH10T3Miag" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div>
       </div>   
      <div>
          <div style="text-align: justify; margin-right: 20px; margin-left: 20px;">
                Amazon Relational Database Service (or Amazon RDS) is a distributed relational database service by Amazon Web Services (AWS).It is a web service running "in the cloud" designed to simplify the setup, operation, and scaling of a relational database for use in applications.Complex administration processes like patching the database software, backing up databases and enabling point-in-time recovery are managed automatically.Scaling storage and compute resources can be performed by a single API call.<br/>



               In November 2014 AWS announced Amazon Aurora, a MySQL-compatible database offering enhanced high availability and performance.
               Amazon Relational Database Service (Amazon RDS) makes it easy to set up, operate, and scale a relational database in the cloud. It provides cost-efficient and resizable capacity while automating time-consuming administration tasks such as hardware provisioning, database setup, patching and backups. It frees you to focus on your applications so you can give them the fast performance, high availability, security and compatibility they need.<br/><br>
               <b><h2>Amazon RDS Engines</h2></b><hr>

               Amazon RDS is available on several database instance types - optimized for memory, performance or I/O - and provides you with six familiar database engines to choose from, including Amazon Aurora, PostgreSQL, MySQL, MariaDB, Oracle, and Microsoft SQL Server. You can use the AWS Database Migration Service to easily migrate or replicate your existing databases to Amazon RDS.<br/>
               Amazon RDS was first released on 22 October 2009, supporting MySQL databases. This was followed by support for Oracle Database in June 2011, Microsoft SQL Server in May 2012,PostgreSQL in November 2013,and MariaDB (a fork of MySQL) in October 2015.<br/>
               In November 2014 AWS announced Amazon Aurora, a MySQL-compatible database offering enhanced high availability and performance.<br>
               Amazon RDS gives you access to the capabilities of a MySQL, MariaDB, PostgreSQL, Microsoft SQL Server, Oracle, or Amazon Aurora database server. These capabilities mean that the code, applications, and tools you already use today with your existing databases work with Amazon RDS without modification. Amazon RDS automatically backs up your database and maintains the database software that powers your DB instance. Amazon RDS is flexible: you can scale your DB instance's compute resources and storage capacity to meet your application's demand. As with all Amazon Web Services, there are no up-front investments, and you pay only for the resources you use.<br><br>
              <b> <h2>Organisations using Amazon RDS</h2></b><hr>
               Netflix, NASA, Expedia, Slack, Samsung, Nokia, Adobe, Comcat etc.
            </div> 
            </div><hr>
                  <div class="row" id="SupButton">
              <a style=" margin-left: 300px; align-content: center;margin-top: 10px; " class="btn btn-lg btn-default" href="#" role="button"> Link</a>
                 <a style="margin-left: 250px;" class="btn btn-lg btn-default" href="{% url 'mod1:rdssup' %}"" role="button"> Common Support issues</a>
            </div>
    
    
   </div>
  </div>

   <div class="f1" style="color:white;">
      <footer class="site-footer row" style=" background: black; padding-left: 20px;">
       <div class="col-md-6"> <h3>Contact us<br></h3>
          <p>  Email: abc@amazon.com<br>
               Mobile no: +919906810610,+919797108430</p>
       </div>
       <div class="col-md-6" style="text-align: right; padding-right: 50px; padding-top: 20px;">
        <a style="padding-right: 20px; color: white;" href="{% url 'mod1:rdsadvan' %}">Why RDS?</a>
        <a style="color: white;" href="{% url 'mod1:database' %}">Advantages of Database in cloud</a>
       </div> 
      </footer>
    </div>
           

           
       
       
   {% endblock %}